name: Simple File Output

on:
  push:
    branches: [ main ]

jobs:
  write-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create output file
      run: |
        echo "Hello, GitHub Actions!"

